### ISSUE TITLE
[hump.gamestate] textinput callback doesn't work properly

### ISSUE THREAD

**Issue by AbelSaphirion** [vrld/hump#106]
Whenever I'm trying to type any letter or number textinput argument becomes equal to gamestate table.
```
gamestate = require("gamestate")

local state = {}
local check = ""

state.textinput = function(t)
    check = t == state and "true" or "false"
end

state.draw = function()
    love.graphics.print(check, 1, 1)
end

function love.load()
  gamestate.registerEvents()
  gamestate.switch(state)
end
```
prints "true" when typing.

**Comment by flamendless** [comment]
Because you do `state == true` which would always be true if state is not nil. You should do `(state == true) or false`

**Comment by AbelSaphirion** [comment]
My mistake, I used dote instead of colon.
