### ISSUE TITLE
feature request: Timer.yoyo function

### ISSUE THREAD

**Issue by veryrandomname** [vrld/hump#28]
I'd like to be easily able to let something fade in and out again.

Sadly something simple like this won't work:

```
function DrawTimer:yoyo(delay, func)
    self:do_for(delay, func, function() self:do_for(delay, function(dt) func(-dt) end) end)
end

local t = 0
DrawTimer:yoyo(2, function(dt)
    t = t + dt
    print(t)
    love.graphics.setColor( 255, 255, 255, 255 * t/2 )
    love.graphics.draw(card.img,50,450)
    love.graphics.setColor( 255, 255, 255, 255 )
end)
```

The after() part of do_for would execute some big gap after func has finished, thus leaving a time frame where nothing is drawn.

My personal sad fix for this looks like this:

```
function DrawTimer:yoyo(time, func)
    self:add(time-0.01,function() self:do_for(time, function(dt) func(-dt) end) end)
    self:do_for(time, func)
end
```

Maybe you could cook up something useful?

**Comment by vrld** [comment]
can be implemented with [Time.script](http://hump.readthedocs.io/en/latest/timer.html#Timer.script):

    Timer.script(function(wait)
        tweenIn(someTime)
        wait(someTime)
        tweenOut()
    end)
