### ISSUE TITLE
Clarify GameState usage in documentation

### ISSUE THREAD

**Issue by chanko08** [vrld/hump#49]
First off, thank you for having worked on this! I've been using it in Ludum Dare with great success!

In the recently passed Ludum Dare, I ran into an issue where my game state classes would only initialize once. At the time, I decided to just stuff that initialization stuff into the `enter` function and leave it. Now that I have more time though, I was able to check the source code for `GameState` and saw that the `init` method gets set to nil after having it called. This unfortunately sets class methods to nil as well, which caused a bit of confusion for me and possibly others I imagine. Perhaps the documentation should say something about this explicitly, as it is modifying code outside of the library?

A simple example might explain my confusion.

```lua
GS = require 'hump.gamestate'
class = require 'hump.class'

local state1 = class({})
local count = 5

function state1:init()
  print('Init is called only once, despite me switching with a class and not an object')
end

function state1:enter()
  print('Enter is always called')
end

function state1:update()
  --switching with class value, not the object `self`
  count = count - 1
  if count <= 0 then
    love.event.quit()
  end
  GS.switch(state1)
end
``` 

Thoughts? If you'd like, I can make the edit. It looks like it's stored on the `gh-pages` branch, which seems simple enough. Thank you!

**Comment by vrld** [comment]
What do you think about this change of [GS.switch](http://vrld.github.io/hump/#hump.gamestateswitch)?

> Switching a gamestate will call the leave() callback on the current gamestate, replace the current gamestate with to, call the init() function if **and only if** the state was not yet inialized and finally call enter(old_state, ...) on the new gamestate.

Regarding overwriting `init()` with `nil` - you're right, that should change.

**Comment by chanko08** [comment]
That change makes sense to me, thanks for looking into it!

I'm not sure if there's a good solution for the overwriting problem. If the gamestates aren't classes, but more like a singleton object for that game state then it makes sense to overwrite it, or somehow tag it so init isn't called again. I guess it's however you see fit with how the library should work :-)

**Comment by vrld** [comment]
The recent commit 52324d53688a276fc30aec92b573b439798a5b4f that moved the documentation to sphinx/readthedocs.org includes more explicit wording. Together with commit ca7fa8acb302522660e77483d63f06ffd2066204, the issue can be closed.
