### ISSUE TITLE
hump/gamestate.lua:40: attempt to index local 'to'

### ISSUE THREAD

**Issue by TheMeq** [vrld/hump#51]
Hi, I am using hump for the first time and have set up a simple program only using the gamestates module and I have this error: 

    Error
    hump/gamestate.lua:40: attempt to index local 'to' (a boolean value)
    Traceback
    hump/gamestate.lua:40: in function 'switch'
    main.lua:5: in function 'load'
    [C]: in function 'xpcall'

My main.lua is as follows: 

    Gamestate = require("hump.gamestate")
    Splash = require("splash")
    function love.load()
    Gamestate.switch(Splash)
    Gamestate.registerEvents()
    end

My splash.lua is as follows

    Splash = {}
    function Splash:init()
    end
    function Splash:enter()
    end
    function Splash:leave()
    end
    function Splash:update(dt)
    end
    function Splash:draw()
    love.graphics.print("Test",10,10)
    end

Any idea what is causing the issue?

Thanks

**Comment by riidom** [comment]
I am a little rusty, but you should return the Splash table in the last 
line of splash.lua if you require it in main.lua

Am Mi, 07.10. um 16:07 schrieb Richard Sparrow:

**Comment by TheMeq** [comment]
Thanks, that's done it!

#close

**Comment by vrld** [comment]
Indeed, [require](http://www.lua.org/manual/5.1/manual.html#pdf-require) returns whatever the file returns or true, if the file returns nothing:

>  Once a loader is found, `require` calls the loader with a single argument, `modname`. If the loader returns any value, require assigns the returned value to `package.loaded[modname]`. If the loader returns no value and has not assigned any value to `package.loaded[modname]`, then `require` assigns **true** to this entry. In any case, `require` returns the final value of `package.loaded[modname]`.
