### ISSUE TITLE
Gamestates now require an init function

### ISSUE THREAD

**Issue by tesselode** [vrld/hump#52]
This code works:

```lua
gamestate = require 'gamestate'

game = {}
function game:init() end
function game:draw()
  love.graphics.print('hello world')
end

gamestate.switch(game)
gamestate.registerEvents()
```

If you take out game.init, however, there is an error about no init function being found. From using previous versions of hump.gamestate, I assume this isn't supposed to be required.

I assume this was caused by ca7fa8a.

**Comment by vrld** [comment]
I think it might be time for unit tests. Thanks for reporting!
