### ISSUE TITLE
Inconsistent naming in examples in docs

### ISSUE THREAD

**Issue by premek** [vrld/hump#58]
_Camera_, _camera_ and _cam_ are used inconsistently in https://github.com/vrld/hump/blob/master/docs/camera.rst

I love the documentation anyway, thanks :)

**Comment by revolucas** [comment]
I would like to add that some camera examples are wrong. Like the cam:lock(player.x,player.y) example. There is no lock method and this example shows up a few times when explaining lockWindow and lockPosition. I'm confused on how to use lockWindow because of a lack of a real example.
