### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by nagolove** [vrld/hump#62]
Aloha! Documentation link(http://blog.signalsondisplay.com/?p=336) for vector:trimInplace() is dead. What about this link does?

**Comment by vrld** [comment]
The code was more or less taken from that site. The wayback machine still has the referenced code: https://web.archive.org/web/20130512171728/http://blog.signalsondisplay.com/?p=336

In any case, the documentation for [vector:trimInplace() is here](http://hump.readthedocs.org/en/latest/vector.html#vector:trimInplace).
