### ISSUE TITLE
Timer:every doesn't take the timer "lateness" into consideration

### ISSUE THREAD

**Issue by pevzi** [vrld/hump#66]
Basically, `Timer:every` behaves as if it was creating an `after` timer on every timeout. Given that `after` fires _not sooner_ than the given delay, it usually exhibits some "lateness". So, `every` timer accumulates that error with each timeout and e.g. 100 repetitions with 0.1 interval take almost 11 seconds to complete (running at 60 FPS) when they are expected to take `10 + dt` seconds at worst. I can suggest [knife.timer](https://github.com/airstruck/knife/blob/master/knife/timer.lua#L45) and [cron.lua](https://github.com/kikito/cron.lua/blob/master/cron.lua#L77) as some examples of a correct implementation.

**Comment by vrld** [comment]
Fixed with Kingdaro's PR
