### ISSUE TITLE
refactoring the whole code of hump.gamestate in a cleaner way

### ISSUE THREAD

**Issue by passito** [vrld/hump#67]
Hello lovers, this is my first message for the community as i'm very new to LÖVE, and lua (but with a C background ;p)

i'm currently writing a framework for making games development easier a little bit like this one, and i'm currently working on the gamestate library. After a bit of thinking, i maybe found the solution to handle this in a clean way, and it is based on overriding the default love.run function .

Because the main loop of the game actually goes into that function, it becomes obvious than redefining it gives you total control on all the aspects of LÖVE, making it the ideal place to hande the gamestate running / transitionning / whatever.

I'm currently working on that idea and will give you my results, but what do you think about it ?

**Comment by vrld** [comment]
That question is better asked in the [LÖVE forums](https://love2d.org/forums/).

The goal of hump is to add what I think is useful to LÖVE, not change the way LÖVE works, so `hump.gamestate` should not replace the default `love.run`.
