### ISSUE TITLE
Object privacy with hump.class?

### ISSUE THREAD

**Issue by arcticmatt** [vrld/hump#81]
Is there a way to make the state of hump objects private? That is, to do something like [this](https://www.lua.org/pil/16.4.html), but with hump classes.

**Comment by vrld** [comment]
Nope, and it is not planned. I don't think restricting access to fields is a value in itself, especially not with a language like Lua. Most often, one resorts to providing trivial getters and setters, which defeats the purpose of encapsulation.

I also don't think it is needed. If you work alone, you ought to know what you can and what you can't change. If you work on a team, I recommend taking the Python route and agree to not touch variables that begin in an underscore (privacy by convention, if you will). If you write a library, there is no way to tell if a user might need access to a variable. In this case, it is better to document possible side effects. If the user still chooses to write stuff they shouldn't, it's their fault, not yours.

Anyway, if you absolutely need private fields, you can put each class in their own file and put a local table that holds the private vars for each object, like this (untested):

```lua
local privates = setmetatable({}, {__mode = 'k'})
return Class{
  init = function(self, foo)
    privates[self] = {foo = foo}
  end,
  getFoo() = function(self)
    return privates[self].foo
  end
}
```
