### ISSUE TITLE
lua rock

### ISSUE THREAD

**Issue by mischief** [vrld/hump#91]
hello, while it's nice that hump has a rockspec, it's only available via the luarocks.org dev server.

i assume there is a way to configure [loverocks](https://github.com/Alloyed/loverocks) to use a different server, but i think it would be more convenient for many users to simply have the rock available on the standard server.

**Comment by vrld** [comment]
Somehow forgot to close this issue. See commit 7642755b99a42d8f1dec08de0fc497b081cf1752

**Comment by mischief** [comment]
thanks!
