### ISSUE TITLE
Add a vector:angleBetween() function

### ISSUE THREAD

**Issue by dnaf** [vrld/hump#96]
Having an `angleBetween` function would save me a few extra keystrokes when I start up my projects. Something like this:
```lua
function vector:angleBetween(self, other)
    return math.atan2(other.y - self.y, other.x - self.x)
end
```

Note that this is different from `angleTo`, as angleTo returns the directed angle from `self` to `other`, while `angleBetween` would return the angle of the difference vector connecting the two vectors

**Comment by vrld** [comment]
Why not just call `(a-b):angleTo()`?

**Comment by dnaf** [comment]
@vrld A method looks cleaner and is a little more readable, in my opinion. If I want the angle between two points, `a:angleBetween(b)` makes more immediate sense than `(a-b):angleTo()` when read plainly.

**Comment by vrld** [comment]
I'm having trouble to understand what `angleBetween` means. It can't be the angle between two vectors: Consider `a = vector(1,0)` and `b = vector(0,1)` with an internal angle of π/2, yet `a:angleBetween(b)` would be -π/4 (the angle between (1,-1) and (1,0). The "inverse" `b:angleBetween(a)` would be 3/4 π. In contrast, `a:angleTo(b)` and `b:angleTo(a)` are ±π/2 (so it's symmetric apart from winding).

What is the usecase for this?

**Comment by vrld** [comment]
Closing for now
